apiVersion: v1
kind: ReplicationController
metadata:
  name: back
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jpt
        tier: backend
    spec:
      containers:
      - name: back
        image: jptttttt/back
        env:
        - name: mypass
          valueFrom:
            secretKeyRef:
              name: gce-datastore-pass-for-json-encryption
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8888
