apiVersion: v1
kind: ReplicationController
metadata:
  name: front
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jpt
        tier: frontend
    spec:
      containers:
      - name: front
        image: jptttttt/front
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 8080
